name: å®šæ—¶æ›´æ–°refç«™ç‚¹
on:
  schedule: # Run workflow automatically
    - cron: '21 */6 * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

env: # è®¾ç½®ç¯å¢ƒå˜é‡
  TZ: Asia/Shanghai # æ—¶åŒºï¼ˆè®¾ç½®æ—¶åŒºå¯ä½¿é¡µé¢ä¸­çš„`æœ€è¿‘æ›´æ–°æ—¶é—´`ä½¿ç”¨æ—¶åŒºæ—¶é—´ï¼‰

jobs:
  build: # è‡ªå®šä¹‰åç§°
    runs-on: ubuntu-latest # è¿è¡Œåœ¨è™šæ‹Ÿæœºç¯å¢ƒubuntu-latest
    steps:
      - name: Checkout # æ­¥éª¤1
        uses: actions/checkout@v1 # ä½¿ç”¨çš„åŠ¨ä½œã€‚æ ¼å¼ï¼šuserName/repoNameã€‚ä½œç”¨ï¼šæ£€å‡ºä»“åº“ï¼Œè·å–æºç ã€‚ å®˜æ–¹actionsåº“ï¼šhttps://github.com/actions
        with:
          ref: 'main'
          repository: 'jaywcjlove/reference'
      - name: Install and Build ğŸ”§
        run: |
          ls -al /home/runner/work/eryajf/reference
          echo -e 'REF_URL=https://wiki.eryajf.net/\nREF_LABEL=äºŒä¸«è®²æ¢µ' > .env
          npm install
          npm run build

      # åˆ©ç”¨actionæŠŠbuildå¥½çš„æ–‡ä»¶ä¸Šä¼ åˆ°æœåŠ¡å™¨/home/eryajf.github.ioè·¯å¾„ä¸‹,éœ€è¦ç¡®è®¤æ­¤ç›®å½•å·²åœ¨æœåŠ¡ç«¯åˆ›å»º
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'   #ssh user name
          port: '22' # è¿œç¨‹æœåŠ¡å™¨sshç«¯å£ï¼Œé»˜è®¤22
          server: '8.136.215.57' # è¿œç¨‹æœåŠ¡å™¨IP
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # è®¤è¯æœåŠ¡å™¨ç§˜é’¥å¯¹çš„ç§é’¥
          local_path: './dist/*'  # å¯¹åº”æˆ‘ä»¬é¡¹ç›®æ‰“åŒ…åçš„é™æ€æ–‡ä»¶è·¯å¾„
          remote_path: '/data/www/ref.eryajf.net' # æœåŠ¡å™¨ä¸Šçš„è·¯å¾„
          delete_remote_files: true